// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrgXDimension.Models;

namespace OrgXDimension.Migrations
{
    [DbContext(typeof(OrgXDimensionContext))]
    [Migration("20201115140508_organisationx")]
    partial class organisationx
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OrgXDimension.Models.ApplicatonItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<string>("Attrition");

                    b.Property<string>("BusinessTravel");

                    b.Property<int>("DailyRate");

                    b.Property<string>("Department");

                    b.Property<int>("DistanceFromHome");

                    b.Property<int>("Education");

                    b.Property<string>("EducationField");

                    b.Property<int>("EmployeeCount");

                    b.Property<int>("EmployeeNumber");

                    b.Property<int>("EnvironmentSatisfaction");

                    b.Property<string>("Gender");

                    b.Property<int>("HourlyRate");

                    b.Property<int>("JobInvolvement");

                    b.Property<int>("JobLevel");

                    b.Property<string>("JobRole");

                    b.Property<string>("MaritalStatus");

                    b.Property<int>("MonthlyIncome");

                    b.Property<int>("MonthlyRate");

                    b.Property<int>("NumCompaniesWorked");

                    b.Property<string>("Over18");

                    b.Property<string>("OverTime");

                    b.Property<int>("PercentSalaryHike");

                    b.Property<int>("PerformanceRating");

                    b.Property<int>("RelationshipSatisfaction");

                    b.Property<int>("StandardHours");

                    b.Property<int>("StockOptionLevel");

                    b.Property<int>("TotalWorkingYears");

                    b.Property<int>("TrainingTimesLastYear");

                    b.Property<int>("WorkLifeBalance");

                    b.Property<int>("YearsAtCompany");

                    b.Property<int>("YearsInCurrentRole");

                    b.Property<int>("YearsSinceLastPromotion");

                    b.Property<int>("YearsWithCurrManager");

                    b.HasKey("Id");

                    b.ToTable("ApplicatonItems");
                });
#pragma warning restore 612, 618
        }
    }
}
